Layout/LineLength:
  Exclude:
    - 'lib/loggable_activity/services/payloads_builder.rb'
    - 'lib/loggable_activity/hooks.rb'
    - 'lib/loggable_activity/activity.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/loggable_activity/encryption.rb'
Metrics/BlockLength:
  Exclude:
    - 'test/dummy/config/environments/development.rb'
    - 'loggable_activity.gemspec'
    - 'test/dummy/db/schema.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/loggable_activity/services/update_payloads_builder.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/loggable_activity/services/update_payloads_builder.rb'
    - 'lib/loggable_activity/services/destroy_payloads_builder.rb'
    - 'lib/loggable_activity/services/base_payloads_builder.rb'
    - 'lib/loggable_activity/hooks.rb'
    - 'lib/loggable_activity/encryption.rb'
    - 'lib/loggable_activity/activity.rb'
Style/Documentation:
  Exclude:
    - 'test/**/*'
