AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/presenters/loggable/presentation_builder.rb'
Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/loggable/activities.rb'
Metrics/AbcSize:
  Exclude:
    - 'app/models/loggable/activity.rb'
    - 'app/services/loggable/encryption.rb'
    - 'app/services/loggable/update_payloads_builder.rb'
