User: 
  record_display_name: full_name
  loggable_attrs: 
    - first_name
    - last_name 
    - age 
    - email
    - role
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - city
        - country
        - postal_code
    - belongs_to: :demo_club
      model: Demo::Club
      loggable_attrs:
        - name
Demo::Address: 
  record_display_name: full_address
  actor_display_name: email
  loggable_attrs:
    - street
    - city
    - country
    - postal_code
  auto_log:
    - create
    - update
    - destroy
Demo::Product:
  loggable_attrs:
    - name
    - description
    - price
    - part_number
  auto_log:
    - create
    - update
    - destroy
Demo::Club: 
  record_display_name: name 
  loggable_attrs: 
    - name
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - city
        - country
        - postal_code
Demo::Journal: 
  record_display_name: title 
  loggable_attrs: 
    - title 
    - body
    - state
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :doctor
      model: User 
      data_owner: true
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - role
    - belongs_to: :patient
      model: User 
      data_owner: true
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - age 
        - role