User: 
  loggable_attrs: 
    - first_name
    - last_name 
    - bio
    - email
  obfuscate_attrs: 
    - email
    - first_name
    - last_name
    - bio 
  relations:
    belongs_to:
      - model: Demo::Address
        on_obfuscate: :nullify
        loggable_attrs:
          - street
          - city
          - country
          - postal_code
        obfuscate:
          - street
          - city
          - country
          - postal_code
      - model: Demo::Product
Demo::Address: 
  loggable_attrs:
    - street
    - city
    - country
    - postal_code
  obfuscate:
    - street
    - city
    - country
    - postal_code