user: 
  loggable_attrs: 
    - first_name
    - last_name 
    - bio
    - email
  obfuscate_attrs: 
    - email
    - first_name
    - last_name
    - bio 
  relations:
    belongs_to:
      - model: Demo::Address
        loggable_attrs:
          - street
          - city
          - state
          - zip
        obfuscate:
          - street
          - city
          - state
          - zip