require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/demo/clubs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Demo::Club. As you add validations to Demo::Club, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Demo::Club.create! valid_attributes
      get demo_clubs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      club = Demo::Club.create! valid_attributes
      get demo_club_url(club)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_demo_club_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      club = Demo::Club.create! valid_attributes
      get edit_demo_club_url(club)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Demo::Club" do
        expect {
          post demo_clubs_url, params: { demo_club: valid_attributes }
        }.to change(Demo::Club, :count).by(1)
      end

      it "redirects to the created demo_club" do
        post demo_clubs_url, params: { demo_club: valid_attributes }
        expect(response).to redirect_to(demo_club_url(Demo::Club.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Demo::Club" do
        expect {
          post demo_clubs_url, params: { demo_club: invalid_attributes }
        }.to change(Demo::Club, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post demo_clubs_url, params: { demo_club: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested demo_club" do
        club = Demo::Club.create! valid_attributes
        patch demo_club_url(club), params: { demo_club: new_attributes }
        club.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the demo_club" do
        club = Demo::Club.create! valid_attributes
        patch demo_club_url(club), params: { demo_club: new_attributes }
        club.reload
        expect(response).to redirect_to(demo_club_url(club))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        club = Demo::Club.create! valid_attributes
        patch demo_club_url(club), params: { demo_club: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested demo_club" do
      club = Demo::Club.create! valid_attributes
      expect {
        delete demo_club_url(club)
      }.to change(Demo::Club, :count).by(-1)
    end

    it "redirects to the demo_clubs list" do
      club = Demo::Club.create! valid_attributes
      delete demo_club_url(club)
      expect(response).to redirect_to(demo_clubs_url)
    end
  end
end
