require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/demo/journals", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Demo::Journal. As you add validations to Demo::Journal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Demo::Journal.create! valid_attributes
      get demo_journals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      journal = Demo::Journal.create! valid_attributes
      get demo_journal_url(journal)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_demo_journal_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      journal = Demo::Journal.create! valid_attributes
      get edit_demo_journal_url(journal)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Demo::Journal" do
        expect {
          post demo_journals_url, params: { demo_journal: valid_attributes }
        }.to change(Demo::Journal, :count).by(1)
      end

      it "redirects to the created demo_journal" do
        post demo_journals_url, params: { demo_journal: valid_attributes }
        expect(response).to redirect_to(demo_journal_url(Demo::Journal.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Demo::Journal" do
        expect {
          post demo_journals_url, params: { demo_journal: invalid_attributes }
        }.to change(Demo::Journal, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post demo_journals_url, params: { demo_journal: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested demo_journal" do
        journal = Demo::Journal.create! valid_attributes
        patch demo_journal_url(journal), params: { demo_journal: new_attributes }
        journal.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the demo_journal" do
        journal = Demo::Journal.create! valid_attributes
        patch demo_journal_url(journal), params: { demo_journal: new_attributes }
        journal.reload
        expect(response).to redirect_to(demo_journal_url(journal))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        journal = Demo::Journal.create! valid_attributes
        patch demo_journal_url(journal), params: { demo_journal: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested demo_journal" do
      journal = Demo::Journal.create! valid_attributes
      expect {
        delete demo_journal_url(journal)
      }.to change(Demo::Journal, :count).by(-1)
    end

    it "redirects to the demo_journals list" do
      journal = Demo::Journal.create! valid_attributes
      delete demo_journal_url(journal)
      expect(response).to redirect_to(demo_journals_url)
    end
  end
end
